# name: Generate Snake Contribution

# on:
#   schedule:
#     # Runs daily to update the snake
#     - cron: "0 0 * * *"
#   workflow_dispatch:

# jobs:
#   generate-snake:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Generate Snake
#         uses: Platane/snk@v3
#         with:
#           github_user_name: ${{ github.repository_owner }}
#           # Customize your snake (optional):
#           # color: "#f75c7e"        # Hex color code
#           # output: dist/snake.svg  # Output path
#           # density: high           # Commit density (low/medium/high)

#       - name: Commit and push
#         run: |
#           git config --local user.name "sir-mammut"
#           git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
#           git add .
#           git commit -m "Update snake contribution graph"
#           git push


name: Generate snake game

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Sutil/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake2.svg
          snake_color: 'blue'

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  